version: 1

base: true

languages:
  - kotlin
  - java

frameworks:
  - spring

builds:
  - gradle

tools:
  - detekt
  - ktlint
  - checkstyle
  - pmd
  - spotbugs
  - archunit
  - kover

runtimes:
  - mise
